{% set name = "mujs" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mujs.com/downloads/mujs-{{ version }}.tar.gz
  sha256: c015475880f6a382e706169c94371a7dd6cc22078832f6e0865af8289c2ef42b
  patches:
    - make.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - readline

test:
  commands:
    - touch test.c && mujs -s test.c

about:
  home: https://mujs.com
  summary: 'MuJS is a lightweight Javascript interpreter designed for embedding in other software to extend them with scripting capabilities.'
  description: |
    MuJS was designed with a focus on small size, correctness, and simplicity.
    It is written in portable C and implements ECMAScript as specified by ECMA-262.
    The interface for binding with native code is designed to be as simple as 
    possible to use, and is very similar to Lua. There is no need to interact with 
    byzantine C++ template mechanisms, or worry about marking and unmarking garbage 
    collection roots, or wrestle with obscure build systems.
  license: ISC
  license_family: Other
  license_file: COPYING
  doc_url: https://mujs.com/reference.html
  dev_url: https://git.ghostscript.com/?p=mujs.git

extra:
  recipe-maintainers:
    - jan-janssen
